Traceback (most recent call last):
  File "C:\Users\Alex L\Downloads\Github\mechanical-engineering-metrology-and-measurements\.venv\Lib\site-packages\jupyter_core\utils\__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Alex L\Downloads\Github\mechanical-engineering-metrology-and-measurements\.venv\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\Alex L\Downloads\Github\mechanical-engineering-metrology-and-measurements\.venv\Lib\site-packages\nbclient\client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alex L\Downloads\Github\mechanical-engineering-metrology-and-measurements\.venv\Lib\site-packages\jupyter_core\utils\__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alex L\AppData\Roaming\uv\python\cpython-3.12.11-windows-x86_64-none\Lib\asyncio\base_events.py", line 691, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Alex L\Downloads\Github\mechanical-engineering-metrology-and-measurements\.venv\Lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Users\Alex L\Downloads\Github\mechanical-engineering-metrology-and-measurements\.venv\Lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\Alex L\Downloads\Github\mechanical-engineering-metrology-and-measurements\.venv\Lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
K = np.diff(y)/np.diff(x)
print K
------------------


  [36mCell[39m[36m [39m[32mIn[12][39m[32m, line 2[39m
[31m    [39m[31mprint K[39m
    ^
[31mSyntaxError[39m[31m:[39m Missing parentheses in call to 'print'. Did you mean print(...)?


